services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: armoiar_production
      POSTGRES_USER: armoiar
      POSTGRES_PASSWORD: secure_password_123
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U armoiar -d armoiar_production"]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    build: .
    ports:
      - "3000:3000"
    environment:
      RAILS_ENV: production
      DATABASE_URL: postgres://armoiar:secure_password_123@db:5432/armoiar_production
      SECRET_KEY_BASE: 1c8bc254011308703d5c4e701784bf737cda569d35e7f91311026db936679a4ce69f202f0fc36abbd15f082c5c23ef354493dcf499eac212ec817933e444f924
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./storage:/app/storage
    command: bundle exec rails server -b 0.0.0.0

volumes:
  postgres_data:
